  sudo: false

  language: java

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - oraclejdk7
#  - openjdk8


# blocklist
  branches:
    except:

# safelist
  branches:
    only:
    
  script:
#    - mvn -e -fn -DskipTests=true install prepare-package

  notifications:
    email:
      - ns68751+tci@gmail.com
